KPI_Dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.shortcuts import include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('resultsFramework.urls'), name='resultsFramework_urls'),
    path('report/', include('masterReport.urls'), name='masterReport_urls'),
    path('accounts/', include('userManagement.urls'), name='userManagement_urls'),
    path('comment/', include('comment.urls')),
    path('api/', include('comment.api.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('chat/', include('interactions.urls', namespace='interactions')),
    # path('api-auth/', include('rest_framework.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

User_Admin/urls.py
from django.urls import path
from .views import (
    dashboard_setting,setting_delete,edit_setting , addsetting
)
urlpatterns = [
    path('', dashboard_setting, name="user-admin-dashboard-setting"),
    path('addsetting/', addsetting, name='addsetting'),
    path('setting_delete/<int:id>/', setting_delete, name='setting_delete'),
    path('setting_edit/<int:id>/', edit_setting, name='edit_setting'),
]

interactions/urls.py
from django.urls import path

from .views import (
    ComposeNewMessage,
    DeletedMessageList,
    DeleteMessage,
    DeleteMessages,
    MessageDetail,
    SentMessages,
    count_new_messages,
    get_messages,
    index,
    mark_as_read,
    send_message,
)

app_name = "interactions"
urlpatterns = [
    path('', index, name='index'),
    path('with-user/<int:user_id>', get_messages, name='get_messages'),
    path('new-message-count/<int:user_id>', count_new_messages, name='count_new_messages'),
    path('mark-as-read/<int:user_id>', mark_as_read, name='mark_as_read'),
    path('send-message', send_message),
    path('compose-message', ComposeNewMessage.as_view(), name='compose_new_message'),
    path('sent-messages', SentMessages.as_view(), name='sent_messages'),
    path('message/<message_id>', MessageDetail.as_view(), name='message_detail'),
    path('delete-message/<message_id>', DeleteMessage.as_view(), name='delete_message'),
    path('delete-messages', DeleteMessages.as_view(), name='delete_messages'),
    path('sent-messages/trash', DeletedMessageList.as_view(), name='deleted_message_list'),
]

interactions/models.py
from django.db import models
from django.db.models import Q
from django.utils import timezone
from userManagement.models import Account
from channels.layers import get_channel_layer


channel_layer = get_channel_layer()

class Message(models.Model):
    content = models.TextField()
    sender = models.ForeignKey(to=Account, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(to=Account, on_delete=models.CASCADE, related_name='receiver')
    created_at = models.DateTimeField(auto_now_add=True)


class UnReadMessage(models.Model):
    message = models.OneToOneField(to=Message, on_delete=models.CASCADE, related_name='new_message')

    @staticmethod
    def count_messages(sender_id, receiver_id) -> int:
        return UnReadMessage.objects.filter(Q(message__sender__id=sender_id) & Q(message__receiver__id=receiver_id)).count()

    @staticmethod
    def clean_unread_message(sender_id: int, receiver_id: int):
        pass


class BroadcastMedium(models.Model):
    CODE_CHOICES = [
        ('sms', 'sms'),
        ('email', 'email'),
        ('whatsapp', 'whatsapp'),
    ]
    name = models.CharField(max_length=100, unique=True)
    code = models.CharField(max_length=10, unique=True, choices=CODE_CHOICES)

    def __str__(self):
        return self.name


class BroadcastMessage(models.Model):
    sender = models.ForeignKey(to=Account, on_delete=models.CASCADE, related_name="sent_broadcast_messages")
    receivers = models.ManyToManyField(to=Account, related_name='received_broadcast_messages')
    subject = models.CharField(max_length=200, null=True, blank=True)
    content = models.TextField()
    is_active = models.BooleanField(default=True)
    medium = models.ManyToManyField(to=BroadcastMedium)
    sent_at = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return self.subject

interactions/views.py
from typing import Sequence
import threading

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from userManagement.models import Account

from .models import BroadcastMessage, Message, BroadcastMedium
from .models import UnReadMessage as NewMessage
from .utils import handle_broadcast_message


@login_required
def index(request):
    user:Account = request.user
    if any([user.is_hopr, user.is_mopd, user.is_dpg]):
        users_list = Account.objects.exclude(id=request.user.id)
    else:
        users_list = Account.objects.filter(Q(is_hopr=True) | Q(is_mopd=True) | Q(is_dpg=True)).exclude(id=request.user.id)
    return render(request, 'interactions/chat-new.html', {
        'users_list': users_list,
    })

message_in_template = """<div class="message received">{message_content}</div>"""
message_out_template= """<div class="message sent">{message_content}</div>"""

@csrf_exempt
def get_messages(request, user_id:int):
    html_text = ""
    messages: Sequence[Message] = Message.objects.filter(
        (Q(sender=request.user) & Q(receiver__id=user_id)) | (Q(sender__id=user_id) & Q(receiver=request.user))
    ).order_by('id')
    for message in messages:
        # t_str = message.created_at.strftime("%b %d %Y %H:%M")
        if message.sender.id == user_id:
            msg_temp = message_in_template.format(message_content=message.content)
        else:
            msg_temp = message_out_template.format(message_content=message.content)
        html_text += msg_temp
    return JsonResponse({
        'data': html_text
    })

@csrf_exempt
def count_new_messages(request, user_id):
    count = NewMessage.count_messages(user_id, request.user.id)
    return JsonResponse({
        'data': count
    })

@csrf_exempt
def mark_as_read(request, user_id):
    qs = NewMessage.objects.filter(Q(message__sender__id=user_id) & Q(message__receiver__id=request.user.id))
    qs.delete()
    return JsonResponse({
        'data': 0
    })

@csrf_exempt
@login_required
def send_message(request):
    print('post data')
    print(request.POST)
    message = request.POST.get('content')
    account_id = request.POST.get('user_id')
    receiver = get_object_or_404(Account, id=account_id)
    Message.objects.create(
        content=message,
        sender=request.user,
        receiver=receiver,
    )
    return JsonResponse({
        'data': True,
    })


# mopd decorator
@method_decorator(login_required, name='dispatch')
class ComposeNewMessage(View):

    def get(self, request):
        receivers = Account.objects.all().exclude(id=request.user.id)
        return render(request, 'interactions/compose_message1.html', {
            'account_list': receivers,
            'medium_list': BroadcastMedium.objects.all(),
        })

    def post(self, request):
        receivers_id = request.POST.getlist('compose_to')
        receivers = Account.objects.filter(id__in=receivers_id)
        subject = request.POST.get('compose_subject', '')
        content = request.POST.get('message_content')
        medium_ids = request.POST.getlist('medium')
        if not medium_ids:
            mediums = BroadcastMedium.objects.all()
        else:
            mediums = BroadcastMedium.objects.filter(id__in=medium_ids)
        bcast_message = BroadcastMessage.objects.create(
            sender=request.user,
            subject=subject,
            content=content,
        )
        bcast_message.receivers.set(receivers)
        bcast_message.medium.set(mediums)
        t = threading.Thread(target=handle_broadcast_message, args=[bcast_message, ])
        t.daemon = True
        t.start()
        return render(request, 'interactions/compose_message.html', {
            'account_list': receivers,
        })


class SentMessages(View):
    
    @method_decorator(login_required)
    def get(self, request):
        message_list = BroadcastMessage.objects.filter(Q(sender=request.user) & Q(is_active=True)).order_by('-id')
        return render(request, 'interactions/message_list.html', {
            'message_list': message_list,
        })


class MessageDetail(View):

    @method_decorator(login_required)
    def get(self, request, message_id):
        message = get_object_or_404(BroadcastMessage, id=message_id)
        prev_m = BroadcastMessage.objects.filter(Q(id__lt=message_id)).last()
        next_m =  BroadcastMessage.objects.filter(Q(id__gt=message_id)).first()
        return render(request, 'interactions/message_detail.html', {
            'message': message,
            'prev_id': prev_m.id if prev_m else 0,
            'next_id': next_m.id if next_m else 0,
        })


class DeleteMessages(View):
    
    @method_decorator(login_required)
    def post(self, request):
        message_id_list = request.POST.getlist('messageId')
        message_list = BroadcastMessage.objects.filter(id__in=message_id_list)
        for m in message_list:
            m.is_active = False
            m.save()
        return redirect('interactions:sent_messages')


class DeleteMessage(View):

    @method_decorator(login_required)
    def get(self, request, message_id):
        message = get_object_or_404(BroadcastMessage, id=message_id)
        if message.is_active:
            message.is_active = False
            message.save()
        else:
            message.delete()
        return redirect('interactions:sent_messages')


class DeletedMessageList(View):
    
    @method_decorator(login_required)
    def get(self, request):
        message_list = BroadcastMessage.objects.filter(Q(sender=request.user) & Q(is_active=False)).order_by('-id')
        return render(request, 'interactions/deleted_messages.html', {
            'message_list': message_list,
        })

interactions/templates/interactions/chat-new.html
{% extends "lte_base.html" %}
{% load static %}
{% block title %}
    Chat
{% endblock %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'interactions/chat.css' %}">
{% endblock %}
{% block content %}
    <div id="chat-container">
        <div id="people-list" style="background-color: green;">
            {% for user in users_list%}
                <div id="userList{{user.id}}" class="person" onclick="selectPerson(this, {{ user.id }})">{{ user }}
                    <span id="unreadMessageCount" class="badge badge-circle" style="background-color: rgb(170, 9, 9); color: black;"></span>
                    <!-- <div id="activeUserIcon" class="symbol-badge bg-success start-100 top-100 border-4 h-8px w-8px ms-n2 mt-n2" style="display: block;"></div> -->
                </div>
            {% endfor %}
        </div>

        <div id="message-box">
            <div id="messages" class="message-container">
                <!-- Messages will be displayed here -->
            </div>

            <div id="input-container">
                <input type="text" id="message-input" placeholder="Type your message..." onkeypress="">
                <button id="send-button" onclick="sendMessage()">Send</button>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'interactions/chatx.js' %}"></script>
    <script>
        function selectPerson(element, user_id) {
            // Remove 'active' class from all person elements
            var people = document.querySelectorAll('.person');
            people.forEach(function(person) {
                person.classList.remove('active');
            });

            // Add 'active' class to the clicked person element
            element.classList.add('active');
            activateChatUser(user_id)
        }

        function sendMessage() {
            const messageInput = document.getElementById('message-input').value;
            var message = messageInput.trim()
            if ( message !== '') {
                document.getElementById('messages').innerHTML += `<div class="message sent">${messageInput}</div>`;
                document.getElementById('message-input').value = '';
                sendMessageSocket(message);
            }
            scrollChatBox();
        }

        var input_box = document.getElementById('message-input');
        input_box.addEventListener('keydown', function(event){
            if (event.keyCode===13){
                sendMessage();
            }
        });
        {% for user in users_list %}
            countNewMessages({{user.id}});
        {% endfor %}
    </script>
{% endblock %}

interactions/templates/interactions/compose_message.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Compose new message
{% endblock %}
{% block content %}
<div class="app-main flex-column flex-row-fluid" id="kt_app_main">
    <!--begin::Content wrapper-->
    <div class="d-flex flex-column flex-column-fluid">
        <!--begin::Toolbar-->
        <div id="kt_app_toolbar" class="app-toolbar py-3 py-lg-6">
            
        </div>
        <!--end::Toolbar-->
        <!--begin::Content-->
        <div id="kt_app_content" class="app-content flex-column-fluid">
            <!--begin::Content container-->
            <div id="kt_app_content_container" class="app-container container-xxl">
                <!--begin::Inbox App - Compose -->
                <div class="d-flex flex-column flex-lg-row">
                    <!--begin::Sidebar-->
                    <div class="d-none d-lg-flex flex-column flex-lg-row-auto w-100 w-lg-275px" data-kt-drawer="true" data-kt-drawer-name="inbox-aside" data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="225px" data-kt-drawer-direction="start" data-kt-drawer-toggle="#kt_inbox_aside_toggle">
                        <!--begin::Sticky aside-->
                        <div class="card card-flush mb-0" data-kt-sticky="true" data-kt-sticky-name="inbox-aside-sticky" data-kt-sticky-offset="{default: false, xl: '100px'}" data-kt-sticky-width="{lg: '275px'}" data-kt-sticky-left="auto" data-kt-sticky-top="100px" data-kt-sticky-animation="false" data-kt-sticky-zindex="95">
                            <!--begin::Aside content-->
                            <div class="card-body">
                                <!--begin::Button-->
                                <a href="{% url 'interactions:compose_new_message' %}" class="btn btn-primary fw-bold w-100 mb-8">New Message</a>
                                <!--end::Button-->
                                <!--begin::Menu-->
                                <div class="menu menu-column menu-rounded menu-state-bg menu-state-title-primary menu-state-icon-primary menu-state-bullet-primary mb-10">
                                    <!--begin::Menu item-->
                                    <div class="menu-item mb-3">
                                        <!--begin::Sent-->
                                        <a href="{% url 'interactions:sent_messages' %}">
                                            <span class="menu-link">
                                                <span class="menu-icon">
                                                    <!--begin::Svg Icon | path: icons/duotune/general/gen016.svg-->
                                                    <span class="svg-icon svg-icon-2 me-3">
                                                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                            <path d="M15.43 8.56949L10.744 15.1395C10.6422 15.282 10.5804 15.4492 10.5651 15.6236C10.5498 15.7981 10.5815 15.9734 10.657 16.1315L13.194 21.4425C13.2737 21.6097 13.3991 21.751 13.5557 21.8499C13.7123 21.9488 13.8938 22.0014 14.079 22.0015H14.117C14.3087 21.9941 14.4941 21.9307 14.6502 21.8191C14.8062 21.7075 14.9261 21.5526 14.995 21.3735L21.933 3.33649C22.0011 3.15918 22.0164 2.96594 21.977 2.78013C21.9376 2.59432 21.8452 2.4239 21.711 2.28949L15.43 8.56949Z" fill="currentColor" />
                                                            <path opacity="0.3" d="M20.664 2.06648L2.62602 9.00148C2.44768 9.07085 2.29348 9.19082 2.1824 9.34663C2.07131 9.50244 2.00818 9.68731 2.00074 9.87853C1.99331 10.0697 2.04189 10.259 2.14054 10.4229C2.23919 10.5869 2.38359 10.7185 2.55601 10.8015L7.86601 13.3365C8.02383 13.4126 8.19925 13.4448 8.37382 13.4297C8.54839 13.4145 8.71565 13.3526 8.85801 13.2505L15.43 8.56548L21.711 2.28448C21.5762 2.15096 21.4055 2.05932 21.2198 2.02064C21.034 1.98196 20.8409 1.99788 20.664 2.06648Z" fill="currentColor" />
                                                        </svg>
                                                    </span>
                                                    <!--end::Svg Icon-->
                                                </span>
                                                <span class="menu-title fw-bold">Sent</span>
                                            </span>
                                        </a>
                                        <!--end::Sent-->
                                    </div>
                                    <!--end::Menu item-->
                                    
                                    <!--begin::Menu item-->
                                    <div class="menu-item">
                                        <!--begin::Trash-->
                                        <a href="{% url 'interactions:deleted_message_list' %}">
                                            <span class="menu-link">
                                                <span class="menu-icon">
                                                    <!--begin::Svg Icon | path: icons/duotune/general/gen027.svg-->
                                                    <span class="svg-icon svg-icon-2 me-3">
                                                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                            <path d="M5 9C5 8.44772 5.44772 8 6 8H18C18.5523 8 19 8.44772 19 9V18C19 19.6569 17.6569 21 16 21H8C6.34315 21 5 19.6569 5 18V9Z" fill="currentColor" />
                                                            <path opacity="0.5" d="M5 5C5 4.44772 5.44772 4 6 4H18C18.5523 4 19 4.44772 19 5V5C19 5.55228 18.5523 6 18 6H6C5.44772 6 5 5.55228 5 5V5Z" fill="currentColor" />
                                                            <path opacity="0.5" d="M9 4C9 3.44772 9.44772 3 10 3H14C14.5523 3 15 3.44772 15 4V4H9V4Z" fill="currentColor" />
                                                        </svg>
                                                    </span>
                                                    <!--end::Svg Icon-->
                                                </span>
                                                <span class="menu-title fw-bold">Trash</span>
                                            </span>
                                        </a>
                                        <!--end::Trash-->
                                    </div>
                                    <!--end::Menu item-->
                                </div>
                                <!--end::Menu-->
                                <!--begin::Menu-->
                                <div class="menu menu-column menu-rounded menu-state-bg menu-state-title-primary">
                                    
                                </div>
                                <!--end::Menu-->
                            </div>
                            <!--end::Aside content-->
                        </div>
                        <!--end::Sticky aside-->
                    </div>
                    <!--end::Sidebar-->
                    <!--begin::Content-->
                    <div class="flex-lg-row-fluid ms-lg-7 ms-xl-10">
                        <!--begin::Card-->
                        <div class="card">
                            <div class="card-header align-items-center">
                                <div class="card-title">
                                    <h2>Compose Message</h2>
                                </div>
                            </div>
                            <div class="card-body p-0">
                                <!--begin::Form-->
                                <form id="kt_inbox_compose_form" method="POST">
                                    {% csrf_token %}
                                    <!--begin::Body-->
                                    <div class="d-block">
                                        {% include "interactions/select_medium_modal.html" %}
                                        <!--begin::To-->
                                        <div class="d-flex align-items-center border-bottom px-8 min-h-50px">
                                            <!--begin::Label-->
                                            <div class="text-dark fw-bold w-75px">To:</div>
                                            <!--end::Label-->
                                            <!--begin::Input-->
                                            <div id="composeList">
                                                <input id="sampleCompose" type="text" style="display: none" value="" name="">
                                            </div>
                                            <input required type="text" class="form-control form-control-transparent border-0"  value="" data-kt-inbox-form="tagify" />
                                            <!--end::Input-->
                                        </div>
                                        <!--end::To-->
                                        <!--begin::Subject-->
                                        <div class="border-bottom">
                                            <input class="form-control form-control-transparent border-0 px-8 min-h-45px" name="compose_subject" placeholder="Subject" />
                                        </div>
                                        <!--end::Subject-->
                                        <!--begin::Message-->
                                        <div id="kt_inbox_form_editor" class="bg-transparent border-0 h-350px px-3"></div>
                                        <!--end::Message-->
                                    </div>
                                    <!--end::Body-->
                                    <!--begin::Footer-->
                                    <div class="d-flex flex-stack flex-wrap gap-2 py-5 ps-8 pe-5 border-top">
                                        <!--begin::Actions-->
                                        <div class="d-flex align-items-center me-3">
                                            <!--begin::Send-->
                                            <div class="btn-group me-4">
                                                <!--begin::Submit-->
                                                <!-- <span class="btn btn-primary fs-bold px-6" data-kt-inbox-form="send">
                                                    <span class="indicator-label">Send</span>
                                                    <span class="indicator-progress">Please wait... 
                                                    <span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
                                                </span> -->
                                                <!--end::Submit onclick="sendMainForm()" -->
                                                <button data-bs-toggle="modal" data-bs-target="#selectMediumModal" class="btn btn-primary" id="submitForm" type="button"> Send </button>
                                            </div>
                                            <!--end::Send-->
                                        </div>
                                        <!--end::Actions-->
                                    </div>
                                    <!--end::Footer-->
                                </form>
                                <!--end::Form-->
                            </div>
                        </div>
                        <!--end::Card-->
                    </div>
                    <!--end::Content-->
                </div>
                <!--end::Inbox App - Compose -->
            </div>
            <!--end::Content container-->
        </div>
        <!--end::Content-->
    </div>
    <!--end::Content wrapper-->
</div>
{% endblock %}

{% block scripts %}
    <script>
        const usersList = [
            {% for acc in account_list %}
            { value: {{ acc.id }}, name : '{{acc.username}}', avatar: '{% if acc.user_image %} {{ acc.user_image.url }} {% else %} /static/mets/avatar/user.png {% endif %}', email: "{{ acc.email }}" },
            {% endfor %}
        ];
    </script>
    
    <script src="{% static 'interactions/compose.js' %}"></script>
{% endblock %}

interactions/templates/interactions/compose_message1.html
{% extends "lte_base.html" %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="../../plugins/summernote/summernote-bs4.min.css">
{% endblock %}
{% block title %}
Compose new message
{% endblock %}
{% block content %}
	<form method="post" action="">
	{% include "interactions/nmodal.html" %}
	{% csrf_token %}
	<section class="content">
	<div class="container-fluid">
		<div class="row">
		<div class="col-md-3">
			<a href="#" class="btn btn-primary btn-block mb-3">Sent Messages</a>

			<div class="card">
			<div class="card-header">
				<h3 class="card-title">Folders</h3>

				<div class="card-tools">
				<button type="button" class="btn btn-tool" data-card-widget="collapse">
					<i class="fas fa-minus"></i>
				</button>
				</div>
			</div>
			<div class="card-body p-0">
				<ul class="nav nav-pills flex-column">
				<li class="nav-item active">
					<a href="#" class="nav-link">
					<i class="fas fa-inbox"></i> Inbox
					<span class="badge bg-primary float-right">12</span>
					</a>
				</li>
				<li class="nav-item">
					<a href="#" class="nav-link">
					<i class="far fa-envelope"></i> Sent
					</a>
				</li>
				<li class="nav-item">
					<a href="#" class="nav-link">
					<i class="far fa-trash-alt"></i> Trash
					</a>
				</li>
				</ul>
			</div>
			<!-- /.card-body -->
			</div>
			<!-- /.card -->
		</div>
		<!-- /.col -->
		<div class="col-md-9">
			<div class="card card-primary card-outline">
			<div class="card-header">
				<h3 class="card-title">Compose New Message</h3>
			</div>


			<!-- /.card-header -->
			<div class="card-body">
				<div class="form-group">
				<label for="cars">Choose Recipent:</label>
				<select name="compose_to" id="recipent" multiple class="form-control">
					{% for account in account_list %}
					<option value="{{ account.id }}">{{ account }}</option>
					{% endfor %}
				</select>
				<!-- <input class="form-control" placeholder="To:"> -->
				</div>
				<div class="form-group">
					<input name="compose_subject" class="form-control" placeholder="Subject:">
				</div>
				<div class="form-group">
					<textarea name="message_content" id="compose-textarea" class="form-control"  placeholder="write message here...">

					</textarea>
				</div>
				<br><br>
				<div class="form-group">
					<p><b>Send Via</b></p>
					{% for med in medium_list %}
						<div class="custom-control custom-checkbox">
							<input name="medium" class="custom-control-input custom-control-input-danger custom-control-input-outline" type="checkbox" id="checkbox{{med.id}}">
							<label for="checkbox{{med.id}}" class="custom-control-label">{{ med }} </label>
						</div>
					{% endfor %}
				</div>
				<!-- <div class="form-group">
					<div class="btn btn-default btn-file">
					<i class="fas fa-paperclip"></i> Attachment
					<input type="file" name="attachment">
					</div>
					<p class="help-block">Max. 32MB</p>
				</div> -->
			</div>
			<!-- /.card-body -->
			<div class="card-footer">
				<div class="float-right">
				<!-- <button type="button" class="btn btn-default"><i class="fas fa-pencil-alt"></i> Draft</button> -->
				<button type="submit" class="btn btn-primary"><i class="far fa-envelope"></i> Send</button>
				<!-- <button  class="btn btn-primary" id="submitForm"
					type="button"> Send </button>
				</div> -->
				<!-- <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> Discard</button> -->
			</div>
			<!-- /.card-footer -->
			</div>
			<!-- /.card -->
		</div>
		<!-- /.col -->
		</div>
		<!-- /.row -->
	</div><!-- /.container-fluid -->
	</section>
</form>
{% endblock %}

{% block scripts %}
<script>
  $(function () {
	//Add text editor
	$('#compose-textarea').summernote()
  })
</script>
<script>
  const usersList = [
	{% for acc in account_list %}
  { value: { { acc.id } }, name: '{{acc.username}}', avatar: '{% if acc.user_image %} {{ acc.user_image.url }} {% else %} /static/mets/avatar/user.png {% endif %}', email: "{{ acc.email }}" },
  {% endfor %}
		];
</script>

<!-- <script src="{% static 'interactions/compose.js' %}"></script> -->
{% endblock %}

interactions/templates/interactions/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat</title>
</head>
<body>
    <h1>Lets chat</h1>
    <form id="form">
        <input type="text" name="message">
        <button type="submit">Send</button>
    </form>
    <div id="messages">

    </div>

    <script type="text/javascript">
        let url = `ws://${window.location.host}/ws/socket-server/`;
        const chatSocket = new WebSocket(url);

        chatSocket.onmessage = function(e){
            let data = JSON.parse(e.data);
            console.log('Data:', data);

            if(data.type==='chat'){
                let messages = document.getElementById('messages');

                messages.insertAdjacentHTML('beforeend', `<div><p>${data.from}: <b>${data.message}</b></p></div>`)
            }
        }

        let form = document.getElementById('form')
        form.addEventListener('submit', (e)=>{
            e.preventDefault()
            let message = e.target.message.value;
            chatSocket.send(JSON.stringify({
                'message':message
            }));
            form.reset();
        });
    </script>
    
</body>
</html>

interactions/templates/interactions/mail_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
</head>
<body>
    <h1>{title}</h1>
    <div style="background-color: bisque;padding:20px;">
        {content}
    </div>
</body>
</html>